### ISSUE TITLE
Receiving "Something broke when playing the track" error.

### ISSUE THREAD

**Issue by TheBwevin** [Cog-Creators/Lavalink-Jars#15]
Hello! I've started receiving this error all of a sudden when trying to play a track from my redbot+lavalink server.
Bot has been running fine for months, usually when I get weird errors I just update either my lavalink.jar or red itself.
Redbot version: 3.5.10
Lavalink version:  3.7.11+red.3

No other changes made, it actually was working fine last night and in the middle of our gaming session it just started displaying this error, couldn't get it working since.

Feel free to ask any additional infos, I will gladly answer as I need to fix this. 😊

Thanks!

Here's my logs:

```
2024-07-11 20:26:42.923  INFO 2656 --- [   XNIO-1 I/O-4] lavalink.server.io.SocketServer          : {"op": "play", "guildId": "247928585720037386", "track": "QAAAhQIAIU15IEZyaWVuZCBmZWF0LiBUYWlsb3IgLSBUaGUgQ2FsbQAKQW5qdW5hZGVlcAAAAAAABWbQAAtoQ0JwTm9tbU1YNAABACtodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PWhDQnBOb21tTVg0AAd5b3V0dWJlAAAAAAAAAAA=", "noReplace": false, "startTime": "0", "pause": false}
2024-07-11 20:26:43.027  INFO 2656 --- [   XNIO-1 I/O-4] lavalink.server.io.SocketServer          : {"op": "voiceUpdate", "guildId": "247928585720037386", "sessionId": "fe4c39e0e0517cfe213c669ca2f8c620", "event": {"token": "579f2483ec969de0", "guild_id": "247928585720037386", "endpoint": "newark225.discord.media:443"}}
2024-07-11 20:26:43.112  WARN 2656 --- [back-1-thread-1] c.s.d.l.s.y.YoutubeAccessTokenTracker    : YouTube auth tokens can't be retrieved because email and password is not set in YoutubeAudioSourceManager, age restricted videos will throw exceptions.
2024-07-11 20:26:43.904 ERROR 2656 --- [back-1-thread-1] .s.d.l.s.y.YoutubeSignatureCipherManager : Problematic YouTube player script /s/player/8d9f6215/player_ias.vflset/en_GB/base.js detected (issue detected with script: no n function match). Dumped to C:\Users\ramir\AppData\Local\Temp\lavaplayer-yt-player-script8146785314382338568.js
2024-07-11 20:26:44.859 ERROR 2656 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of hCBpNommMX4

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:113) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:324) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:1623) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT
  os.arch: amd64
  os.name: Windows 10
  os.version: 10.0
  java.vendor: Oracle Corporation
  java.version: 20.0.2
  java.runtime.version: 20.0.2+9-78
  java.vm.version: 20.0.2+9-78
Caused by: java.lang.RuntimeException: Not success status code: 403
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:124) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
        at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:288) ~[na:na]
        at java.base/java.io.DataInputStream.readByte(DataInputStream.java:268) ~[na:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:46) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:74) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:83) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStaticWithRetry(YoutubeAudioTrack.java:65) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:52) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
        ... 4 common frames omitted

2024-07-11 20:26:45.050  INFO 2656 --- [   XNIO-1 I/O-4] lavalink.server.io.SocketServer          : {"op": "stop", "guildId": "247928585720037386"}
2024-07-11 20:26:47.062  INFO 2656 --- [   XNIO-1 I/O-4] lavalink.server.io.SocketServer          : {"op": "destroy", "guildId": "247928585720037386"}
```

**Comment by aikaterna** [comment]
Please update your bot to the newest Red version and report back after trying again.

**Comment by aikaterna** [comment]
More specifically, we use https://github.com/lavalink-devs/youtube-source now and we have a modified application.yml that manages it - you can download it from our [changelog](https://docs.discord.red/en/stable/changelog.html).

**Comment by TheBwevin** [comment]
Thanks for the quick replys guys!

I've update it yesterday when I saw the issue happening to 3.5.10.
I have also updated the application.yml as mentionned in the post yesterday.

Only changes made to the file was my server password.

**Comment by aikaterna** [comment]
Try this [application.yml](https://cdn.discordapp.com/attachments/321143541638234112/1261068028867510294/application.yml?ex=66919c9f&is=66904b1f&hm=7d7a5f35b4786a44c3f7e06a5397737a429749214ec36152c195a9fb457d307d&) instead.

If it doesn't work, please provide your entire spring.log from startup until you try queueing a track, and the response you get.

**Comment by TheBwevin** [comment]
That actually worked! Thanks a lot!

Would you mind explaining to me what fixed it in this file?

I am by no means an export in coding but I like learning about this kind of stuff to better my knowledge.

Cheers!

**Comment by TheBwevin** [comment]
I think I actually had "youtube" set to "true" in the server section, is it normal for it to be "false" ?

**Comment by aikaterna** [comment]
A couple things here: yes, the built in youtube source needed to be false, with the plugin being true. You would have gotten that 403 Forbidden message if that was the case, before I linked a new application.yml.

Secondly, if you really were getting 403's with our application.yml that is on the release notes, then what we added to make it work now was a configuration block for the plugin that some people will end up needing for success - I intend to make a PR for this when I can get back to a computer.

**Comment by TheBwevin** [comment]
Good to know then!

Thanks again for the help, keep up the great work :D

**Comment by laggron42** [comment]
> Try this [application.yml](https://cdn.discordapp.com/attachments/321143541638234112/1261068028867510294/application.yml?ex=66919c9f&is=66904b1f&hm=7d7a5f35b4786a44c3f7e06a5397737a429749214ec36152c195a9fb457d307d&) instead.
> 
> If it doesn't work, please provide your entire spring.log from startup until you try queueing a track, and the response you get.

Hey @aikaterna, the link is dead, could you reupload it with a permanent URL? I have the same issue described in this issue, and more users could be affecterd in the future too.

**Comment by aikaterna** [comment]
https://gist.github.com/aikaterna/4227dbf1c45640c7ee57cbe36e85ea53

**Comment by laggron42** [comment]
Thanks!

**Comment by fhazal** [comment]
```
[32m       .  [31m _                  _ _       _    [32m__ _ _
[32m      /\\ [31m| | __ ___   ____ _| (_)_ __ | | __[32m\ \ \ \
[32m     ( ( )[31m| |/ _` \ \ / / _` | | | '_ \| |/ /[32m \ \ \ \
[32m      \\/ [31m| | (_| |\ V / (_| | | | | | |   < [32m  ) ) ) )
[32m       '  [31m|_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\[32m / / / /
[0m    =========================================[32m/_/_/_/[0m

	Version:        3.7.12+red.1
	Build time:     21.08.2024 22:57:54 UTC
	Branch          patch/update-koe-v3
	Commit:         2bce42e
	Commit time:    21.08.2024 22:56:39 UTC
	JVM:            17.0.13
	Lavaplayer      1.5.4

2024-11-26 11:47:39.149  INFO 158277 --- [main] lavalink.server.Launcher                 : No active profile set, falling back to 1 default profile: "default"
2024-11-26 11:47:39.867  WARN 158277 --- [main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2024-11-26 11:47:39.891  INFO 158277 --- [main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2024-11-26 11:47:39.892  INFO 158277 --- [main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 737 ms
2024-11-26 11:47:40.802  INFO 158277 --- [main] dev.lavalink.youtube.plugin.PluginInfo   : ********************************************
YOUTUBE-SOURCE VERSION 1.8.3 AVAILABLE
https://github.com/lavalink-devs/youtube-source/releases/tag/1.8.3
Update to ensure the YouTube source remains operational!
********************************************
2024-11-26 11:47:40.866  INFO 158277 --- [main] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2024-11-26 11:47:41.193  INFO 158277 --- [main] d.l.youtube.plugin.YoutubePluginLoader   : YouTube source initialised with clients: WEB_REMIX, WEB, ANDROID_TESTSUITE, TVHTML5_SIMPLY_EMBEDDED_PLAYER, ANDROID_LITE, MEDIA_CONNECT_FRONTEND, IOS 
2024-11-26 11:47:41.206  WARN 158277 --- [main] l.server.config.SentryConfiguration      : Turning off sentry
2024-11-26 11:47:41.383  INFO 158277 --- [main] lavalink.server.config.KoeConfiguration  : OS: LINUX, Arch: X86_64
2024-11-26 11:47:41.384  INFO 158277 --- [main] lavalink.server.config.KoeConfiguration  : Enabling JDA-NAS
2024-11-26 11:47:41.388  INFO 158277 --- [main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: loading with filter null
2024-11-26 11:47:41.393  INFO 158277 --- [main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: successfully loaded.
2024-11-26 11:47:41.640  INFO 158277 --- [main] io.undertow                              : starting server: Undertow - 2.2.16.Final
2024-11-26 11:47:41.646  INFO 158277 --- [main] org.xnio                                 : XNIO version 3.8.6.Final
2024-11-26 11:47:41.654  INFO 158277 --- [main] org.xnio.nio                             : XNIO NIO Implementation Version 3.8.6.Final
2024-11-26 11:47:41.715  INFO 158277 --- [main] org.jboss.threads                        : JBoss Threads version 3.1.0.Final
2024-11-26 11:47:41.747  INFO 158277 --- [main] o.s.b.w.e.undertow.UndertowWebServer     : Undertow started on port(s) 2333 (http)
2024-11-26 11:47:41.752  INFO 158277 --- [main] lavalink.server.Launcher                 : Started Launcher in 2.652 seconds (JVM running for 4.43)
2024-11-26 11:47:41.753  INFO 158277 --- [main] lavalink.server.Launcher                 : Lavalink is ready to accept connections.
2024-11-26 11:47:41.808  INFO 158277 --- [XNIO-1 task-1] io.undertow.servlet                      : Initializing Spring DispatcherServlet 'dispatcherServlet'
2024-11-26 11:47:41.808  INFO 158277 --- [XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2024-11-26 11:47:41.810  INFO 158277 --- [XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
2024-11-26 11:47:41.830  INFO 158277 --- [XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:36376
2024-11-26 11:47:42.092  INFO 158277 --- [XNIO-1 task-1] lavalink.server.io.SocketServer          : Connection successfully established from Red-Lavalink/0.11.0
2024-11-26 11:47:42.123  INFO 158277 --- [XNIO-1 I/O-8] lavalink.server.io.SocketServer          : {"op": "configureResuming", "key": "Red-Core-Audio-977904256373915688-discordbot", "timeout": 60}
2024-11-26 11:47:42.124  WARN 158277 --- [XNIO-1 I/O-8] lavalink.server.io.WebSocketHandler      : Sending websocket commands to Lavalink has been deprecated and will be removed in API version 4. API version 3 will be removed in Lavalink 5. Please use the new REST endpoints instead.
2024-11-26 11:54:56.471  INFO 158277 --- [XNIO-1 I/O-8] lavalink.server.io.SocketServer          : {"op": "play", "guildId": "269801875203817472", "track": "QAAAmwIANVJlbWEsIFNlbGVuYSBHb21leiAtIENhbG0gRG93biAoT2ZmaWNpYWwgTXVzaWMgVmlkZW8pAAxTZWxlbmEgR29tZXoAAAAAAAOpgAALV2NJY1ZhcGZxWHcAAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1XY0ljVmFwZnFYdwAHeW91dHViZQAAAAAAAAAA", "noReplace": false, "startTime": "0", "pause": false}
2024-11-26 11:54:56.933  INFO 158277 --- [XNIO-1 I/O-8] lavalink.server.io.SocketServer          : {"op": "voiceUpdate", "guildId": "269801875203817472", "sessionId": "4bdd6ff7ecfaa8ae992b1a83379ff42d", "event": {"token": "eca3b18e3337a1f8", "guild_id": "269801875203817472", "endpoint": "singapore11039.discord.media:443"}}
2024-11-26 11:54:57.574  INFO 158277 --- [lava-daemon-pool-playback-1-thread-1] d.l.y.http.YoutubeAccessTokenTracker     : Updating YouTube visitor id succeeded, new one is Cgt6ekdJbWFvclhGayiR7pa6BjIKCgJNWRIEGgAgTjoMCAEggY-tvZTi7aJn, next update will be after 600 seconds.
2024-11-26 11:54:57.763 ERROR 158277 --- [lava-daemon-pool-playback-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of WcIcVapfqXw

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-1.5.4.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:113) ~[lavaplayer-1.5.4.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:324) ~[lavaplayer-1.5.4.jar!/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.5.4
  os.arch: amd64
  os.name: Linux
  os.version: 5.15.0-125-generic
  java.vendor: Ubuntu
  java.version: 17.0.13
  java.runtime.version: 17.0.13+11-Ubuntu-2ubuntu122.04
  java.vm.version: 17.0.13+11-Ubuntu-2ubuntu122.04
Caused by: java.io.IOException: Invalid status code for player api response: 403
	at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.assertSuccessWithContent(HttpClientTools.java:154) ~[lavaplayer-1.5.4.jar!/:na]
	at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadJsonResponse(NonMusicClient.java:58) ~[youtube-plugin-1.7.2.jar!/:na]
	at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:97) ~[youtube-plugin-1.7.2.jar!/:na]
	at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35) ~[youtube-plugin-1.7.2.jar!/:na]
	at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:188) ~[youtube-plugin-1.7.2.jar!/:na]
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:114) ~[youtube-plugin-1.7.2.jar!/:na]
	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:72) ~[youtube-plugin-1.7.2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[lavaplayer-1.5.4.jar!/:na]
	... 4 common frames omitted

2024-11-26 11:54:58.291  INFO 158277 --- [XNIO-1 I/O-8] lavalink.server.io.SocketServer          : {"op": "stop", "guildId": "269801875203817472"}
2024-11-26 11:55:00.298  INFO 158277 --- [XNIO-1 I/O-8] lavalink.server.io.SocketServer          : {"op": "destroy", "guildId": "269801875203817472"}
```

i have the same problem, i update to the latest version of redbot but the problem still persist can someone help me ??
