### ISSUE TITLE
Error when i try to play some web radio(.mp3)

### ISSUE THREAD

**Issue by Nico-ITA** [Cog-Creators/Lavalink-Jars#9]
2021-11-16 18:15:11.896 ERROR 5830 --- [ader-2-thread-1] l.server.player.AudioLoaderRestHandler   : Track loading failed

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Could not read the file for detecting file type.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.3.93-original.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.detectContainer(MediaContainerDetection.java:64) ~[lavaplayer-1.3.93-original.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager.detectContainerWithClient(HttpAudioSourceManager.java:142) ~[lavaplayer-1.3.93-original.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager.detectContainer(HttpAudioSourceManager.java:120) ~[lavaplayer-1.3.93-original.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager.loadItem(HttpAudioSourceManager.java:81) ~[lavaplayer-1.3.93-original.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436) ~[lavaplayer-1.3.93-original.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418) ~[lavaplayer-1.3.93-original.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217) ~[lavaplayer-1.3.93-original.jar!/:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.93-original
  os.arch: arm
  os.name: Linux
  os.version: 5.10.17-v7+
  java.vendor: Raspbian
  java.version: 11.0.12
  java.runtime.version: 11.0.12+7-post-Raspbian-2deb10u1
  java.vm.version: 11.0.12+7-post-Raspbian-2deb10u1
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method) ~[na:na]
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115) ~[na:na]
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168) ~[na:na]
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1374) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:985) ~[na:na]
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137) ~[httpcore-4.4.12.jar!/:4.4.12]
	at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:197) ~[httpcore-4.4.12.jar!/:4.4.12]
	at org.apache.http.impl.io.IdentityInputStream.read(IdentityInputStream.java:85) ~[httpcore-4.4.12.jar!/:4.4.12]
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135) ~[httpclient-4.5.10.jar!/:4.5.10]
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252) ~[na:na]
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292) ~[na:na]
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351) ~[na:na]
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:173) ~[lavaplayer-1.3.93-original.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:180) ~[lavaplayer-1.3.93-original.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:186) ~[lavaplayer-1.3.93-original.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.io.SavedHeadSeekableInputStream.read(SavedHeadSeekableInputStream.java:102) ~[lavaplayer-1.3.93-original.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.io.SavedHeadSeekableInputStream.loadHead(SavedHeadSeekableInputStream.java:40) ~[lavaplayer-1.3.93-original.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.detectContainer(MediaContainerDetection.java:56) ~[lavaplayer-1.3.93-original.jar!/:na]

Bot error : Could not read the file for detecting file type.

**Comment by aikaterna** [comment]
What is the url of the stream you tried to play?

**Comment by aikaterna** [comment]
I am closing this due to inactivity and the fact that our builds have changed since this report. If you were having any trouble with a web radio, make sure to try it again with a new build that is fully up to date.
